### ISSUE TITLE
Add Dockerfile with Node.js and Yarn

### ISSUE THREAD

**Issue by janpelikan** [gabrielweyer/azure-vm-pricing#266]
Hi, thanks for creating `azure-vm-pricing` it's a really useful tool.

I'd like to kindly ask if it would be possible to add a Dockerfile to the repository, which would collect all the necessary prerequisites and dependencies (especially Node and Yarn) so that `azure-vm-pricing` could be used in the container.

It's not always possible/wanted to install Node.js on a workstation, but Docker would be a solution.

Thank you very much and have a nice day.

**Comment by gabrielweyer** [comment]
Would you then be happy to build the Docker image yourself or would you expect to be able to pull it from Docker Hub (or another container registry)?

**Comment by janpelikan** [comment]
Frankly, I tried to create a custom container that would use azure-vm-pricing, but with no luck. I can't figure out why. So I was wondering if you could provide a working basis for running azure-vm-pricing in a Dockerfile.

If you could take the time to containerise azure-vm-pricing, Dockerfile alone would be sufficient. No need to add it to Docker Hub right away.

If I can figure it out, I have no problem sending a merge request here to the repository with the addition of a Dockerfile.

**Comment by janpelikan** [comment]
Hello @gabrielweyer, 

I just pushed a pull request #272 with Dockerfile and with a small edits about output files and their destination path. Code is now fully operational (tested on standard Linux laptop and Macbook with Apple Silicon CPU) and in Docker works pretty smooth. 

I was trying do my best, but very likey you'll find some ugly mistake in code. Sorry for that, I am not a TypeScript skilled at all. Feel free edit the code as you wish.

I'll happy for any feedback. Have a nice day.

**Comment by gabrielweyer** [comment]
Hey @janpelikan we created a PR pretty much at the same time! Could you please try out #273 and let me know if it's working on Linux/macOS?

Our approaches are quite similar, the main difference is that you've added the ability to override the output directory to the application code whereas I've done it using a Docker bind.

**Comment by janpelikan** [comment]
@gabrielweyer I'm trying #273 but I can't build a docker image.

```
 => [11/11] RUN yarn install                                                                                                                                                161.5s
 => => # ➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry                                                                        
 => => # ➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry                                                                
 => => # ➤ YN0066: │ typescript@patch:typescript@npm%3A5.3.3#~builtin<compat/typescript>::version=5.3.3&hash=85af82: Cannot apply hunk #1                                          
 => => # ➤ YN0000: └ Completed in 7s 639ms                                                                                                                                         
 => => # ➤ YN0000: ┌ Link step                                                                                                                                                     
 => => # ➤ YN0007: │ puppeteer@npm:21.6.1 must be built because it never has been before or the last one failed
 ```

I can let the build run for any length of time and it still won't finish. I've encountered this before, similar behavior was happening to me before I created. I'm guessing it's because Yarn/Puppeteer is downloading and unpacking Chromium. That takes an awful lot of time for some reason or nothing happen at all. Yet the package (archive) itself, where the binaries and browser libraries are packaged, is under 200MB.

Any ideas, suggestions?

By the way, this weird behaviour during building the image is a reason why I'm using in #272 a Chromium from the Debian repository. Build is finished in minutes. Can you please try it? Maybe it would be possible to efficiently merge our changes together?

**Comment by gabrielweyer** [comment]
It takes a while to build Puppeteer (around 10 minutes on my 10 years old Windows desktop). I would have expected it to be much faster on Apple Silicon.

I'll give your PR a spin, my main concern being that Chromium in the Docker image and the Puppeteer version could get out of sync.
