### ISSUE TITLE
List of OS and Region

### ISSUE THREAD

**Issue by KevM92** [gabrielweyer/azure-vm-pricing#270]
Hi @gabrielweyer,

Thank you for creating this tool. However, I encountered an issue while trying to use it.

1. **Region Selection**: I want to use regions like West Europe or Germany West Central. I tried using region names such as `westeurope`, `weu`, and others. However, I consistently receive the following error:
    ```
    Selecting currency: eur
    Selecting region: westeurope
    UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Failed to select 'westeurope' for selector 'select[name="region"]', instead selected 'us-north-central'".
        at throwUnhandledRejectionsMode (node:internal/process/promises:389:7)
        at processPromiseRejections (node:internal/process/promises:470:17)
        at processTicksAndRejections (node:internal/process/task_queues:96:32) {
      code: 'ERR_UNHANDLED_REJECTION'
    ```
    Could you please provide a list of regions and the correct names to enter in the command, similar to what you did for Culture and Currency?

2. **OS Settings**: Could you also provide a list for the "OS" settings? For example, on the Microsoft site, you can choose options like Red Hat or SharePoint. It would be helpful to have similar options here.

Again, thank you for this awesome tool. I'm sure it will deliver great value once I can use it correctly.

Thanks,
Kev

**Comment by gabrielweyer** [comment]
I added the list of [supported regions](https://github.com/gabrielweyer/azure-vm-pricing?tab=readme-ov-file#supported-regions) and [supported OS/Software](https://github.com/gabrielweyer/azure-vm-pricing?tab=readme-ov-file#supported-ossoftware).

**Comment by KevM92** [comment]
Thanks this is awesome will try later

**Comment by gabrielweyer** [comment]
@KevM92 closing this. Feel free to reopen if the documentation is insufficient.
